[build]
builder = "NIXPACKS"

[deploy]
startCommand = "streamlit run omicare_fraud_app.py --server.port=$PORT --server.address=0.0.0.0"
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
